# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Josef Bisits
email: jbisits@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Josef Bisits
github_username: jbisits
repository: "jbisits/jbisits.github.io"
url : https://jbisits.github.io
baseurl : /
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Australia/Sydney

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Josef Bisits"
  avatar   : "/assets/images/Headshot.jpeg"
  bio      : "PhD candidate - musician"
  location : "Sydney, Australia"
  github   : "jbisits"
  linkedin : "josef-bisits-066253123"
  orcid    : "0000-0002-6340-4470"
  orcid    : "http://orcid.org/0000-0002-6340-4470"
  #links:
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    url: https://github.com/jbisits
  #  - label: "LinkedIn"
  #    icon: "fab fa-fw fa-linkedin"
  #    url: "https://www.linkedin.com/in/josef-bisits-066253123/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:

  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
